base/urls.py
from django.contrib import admin
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.HomeView.as_view(), name = 'home'),
    # path('leads_list', views.LeadListView.as_view(), name = 'leads_list'),
    # path('create', views.LeadCreateView.as_view(), name = "lead_create"),
    # path('detail/<int:pk>', views.LeadDetailView.as_view(), name = 'lead_detail'),
    # path('lead_update/<int:pk>', views.LeadUpdateView.as_view(), name = 'lead_update'),
    # path('lead_delete/<int:pk>', views.LeadDeleteView.as_view(), name = 'lead_delete'),
    # path('assign_agent/<int:pk>', views.AssignAgentView.as_view(), name = "assign_agent"),
    # path('category_update/<int:pk>', views.LeadCategoryUpdateView.as_view(), name = "category_update"),
    # path('category_list', views.CategoryListView.as_view(), name = 'category_list'),
    
    # path('category_detail/<int:pk>', views.CategoryDetailView.as_view(), name = 'category_detail'),

]

shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views

app_name = 'shop' 

urlpatterns = [
    # products
    path('<int:pk>/<int:cat>', views.ProductListView.as_view(), name = 'home'),
    path('<int:pk>/create', views.ProductCreateView.as_view(), name = "product_create"),
    path('delete/<int:pk>', views.ProductDeleteView.as_view(), name = "product_delete"),
    path('update/<int:pk>', views.ProductUpdateView.as_view(), name = "product_update"),
    path('compare/<int:pk>', views.ProductCompareView.as_view(), name = "product_compare"),
    path('<pk>/all', views.ProductListWholeView.as_view(), name = "product_all"),
    
    
    # others
    path('item-create/<int:pk>', views.ItemCreateView.as_view(), name = 'item-create'),
    path('item-update/<int:pk>', views.ItemUpdateView.as_view(), name = 'item-update'),
    path('item-delete/<int:pk>', views.ItemDeleteView.as_view(), name = 'item-delete'),
    path('order-create/<int:pk>', views.OrderCreateView.as_view(), name = 'order-create'),
    path('order-list/<int:pk>', views.OrderListView.as_view(), name = 'order-list'),
    path('order-list-customer/<int:pk>', views.OrderListCustomerView.as_view(), name = 'order-list-customer'),
    path('order-update/<int:pk>', views.OrderUpdateView.as_view(), name = 'order-update'),
    path('order-delete/<int:pk>', views.OrderDeleteView.as_view(), name = 'order-delete'),
    path('order-detail-customer/<int:pk>', views.OrderDetailViewCustomer, name = 'order-detail-customer'),
    path('stock-update/<int:pk>', views.StockUpdateView, name = 'stock-update'),
    path('map-index', views.map_index, name = 'map-index'),


    # categories
    path('<int:pk>/categories', views.category_create, name = 'categories'),
    path('category-delete/<int:pk>', views.category_delete, name = 'category-delete'),
    path('category-detail/<int:pk>', views.CategoryDetailView.as_view(), name = 'category-detail'),


    # suppliers
    path('<int:pk>/suppliers', views.supplier_create, name = 'suppliers'),
    path('supplier-update/<int:pk>', views.SupplierUpdateView.as_view(), name = 'supplier-update'),
    path('supplier-delete/<int:pk>', views.supplier_delete, name = 'supplier-delete'),
    path('supplier-detail/<int:pk>', views.SupplierDetailView.as_view(), name = 'supplier-detail'),

    # slides
    path('slide-create/<int:pk>', views.SlideCreateView.as_view(), name = 'slide-create'),
    path('slide-list/<int:pk>', views.SlideListView.as_view(), name = 'slide-list'),
    path('slide-delete/<int:pk>', views.SlideDeleteView, name = 'slide-delete'),

    # shop
    path('shop-update/<int:pk>', views.ShopUpdateView.as_view(), name = 'shop-update'),
    path('shop-confirm-user', views.confirm_user_view, name = 'confirm-user'),
    path('update-bank-detail/<int:pk>', views.BankDetailUpdateView.as_view(), name = 'update-bank'),

]

smart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
        LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, 
        PasswordResetConfirmView, PasswordResetCompleteView, 
    )
from base.views import SignupView, ProfileDetailView, CartView ,CheckoutDetailView, ProfileUpdateView
from shop.views import payment_handler_with_order_id, success, CheckoutDetailView, payment_handler, ShopCreateView
# from leads.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace = 'base')),
    path('shop/', include('shop.urls', namespace = 'shop')),
    path('login/', LoginView.as_view(),name = 'login'),
    path('logout/', LogoutView.as_view(),name = 'logout'),
    path('profile/<int:pk>', ProfileDetailView.as_view(),name = 'profile'),
    path('profile-update/<int:pk>', ProfileUpdateView.as_view(),name = 'profile-update'),
    path('cart/<int:pk>', CartView,name = 'cart'),
    # path('checkout/<int:pk>', CheckoutDetailView,name = 'checkout'),
    path('checkout/<int:pk>', CheckoutDetailView.as_view(),name = 'checkout'),
    path('signup/', SignupView.as_view(),name = 'signup'),
    # path('password_reset/', PasswordResetView.as_view(),name = 'password_reset'),
    # path('payment/<int:pk>', payment_handler_with_order_id, name = 'payment'),
    path('payment/<int:pk>', payment_handler, name = 'payment'),
    path('success', success, name = 'success-payment'),
    path('password_reset/', PasswordResetView.as_view(),name = 'password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(),name = 'password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name = 'password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(),name = 'password_reset_complete'),

    # shop views
    path("shop_create", ShopCreateView.as_view(), name="shop-create")
    
]

shop/views.py
from urllib import request
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import (
                        ProductModelForm, ProductStockUpdateForm, 
                        CategoryModelForm, ItemModelForm, OrderModelForm, 
                        OrderUpdateModelForm, StockUpdateForm,
                        SlideModelForm, SupplierModelForm, SupplierUpdateForm,
                    )
from django.shortcuts import redirect, reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from base.models import Shop, User
from .models import Product, Category, OrderItem, Order, Cart, StockFile, Item, Slide, Supplier
import razorpay
from django.views.decorators.csrf import csrf_exempt
import pandas as pd
import os
from base.forms import ShopUpdateForm, ShopCreateForm, ConfirmUserForm, UpdateBankDetailsForm
from django.db.models import Sum



from django.core.paginator import Paginator
import folium
import geocoder as gc
from django.contrib.auth.models import auth
from cryptography.fernet import Fernet
# Create your views here.



encryption_key = b"zdeU8DTcUCwtACFlKKwh1lGMOq1i6wd3YmOFduJsfbk="
encrypter = Fernet(encryption_key)


# ******************* SHOP VIEWS ********************


class ShopUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'shop/shop/shop_update.html'
    form_class = ShopUpdateForm
    def get_success_url(self):
        # print(self.object.product.shop)
        # print("asdsadasd")

        return reverse('shop:shop-update', kwargs = {'pk': self.request.user.shop.id})

    def get_queryset(self):
        queryset =Shop.objects.filter(id=self.kwargs['pk'])
        print("inside  get_queryset()")
        print(queryset)
        return queryset
    
    def get_context_data(self, **kwargs):
        shop = Shop.objects.get(id = self.kwargs['pk'])
        form = ShopUpdateForm(instance = shop)
        orders = Order.objects.filter(shop=shop)
        total_sales = Order.objects.filter(shop=shop).aggregate(Sum('price'))
        context = super().get_context_data(**kwargs)
        context.update({
            'shop':shop,
            "form":form,
            "total_sales":total_sales["price__sum"] if total_sales["price__sum"] else 0,
            "order_num":len(orders)
        })
        
        return context
    

class ShopCreateView(LoginRequiredMixin, CreateView):
    template_name = 'shop/shop/shop_create.html'
    form_class = ShopCreateForm
    def get_success_url(self):
        print(self.kwargs) 
        return reverse('shop:home', kwargs = {'pk': self.object.id, 'cat':0})

    def form_valid(self, form):
        shop = form.save(commit=False)
        shop.user = self.request.user
        # print(self.kwargs['pk'])
        pbk = shop.rzp_pb_key
        pbk = encrypter.encrypt(pbk.encode())
        shop.rzp_pb_key = pbk

        prk = shop.rzp_pr_key
        prk = encrypter.encrypt(prk.encode())
        shop.rzp_pr_key = prk

        shop.save()
        return super(ShopCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ShopCreateView, self).get_form_kwargs()
        # kwargs.update({'user': self.request.user})
        return kwargs



class ShopView(LoginRequiredMixin, ListView):
    template_name = 'shop/product_list.html'


def confirm_user_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = None
        user = auth.authenticate(username = username, password = password)
        if user:
            if user==request.user:
                return redirect("shop:update-bank", pk=request.user.shop.id)
            else:
                return HttpResponse("You are not the owner of this shop. Please go back and login as the owner.")
        else:
            return HttpResponse("Authentication Failed. Please go back and try again.")


    else:
        form = ConfirmUserForm()
        return render(request, "shop/shop/confirm_user.html", {"form":form})



class BankDetailUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'shop/shop/update_bank_details.html'
    form_class = UpdateBankDetailsForm
    def get_success_url(self):
        # print(self.object.product.shop)
        # print("asdsadasd")

        return reverse('shop:shop-update', kwargs = {'pk': self.request.user.shop.id})

    def get_queryset(self):
        queryset =Shop.objects.filter(id=self.kwargs['pk'])
        print("inside  get_queryset()")
        print(queryset)
        return queryset
    
    def get_context_data(self, **kwargs):
        shop = Shop.objects.get(id = self.kwargs['pk'])
        form = UpdateBankDetailsForm(instance = shop)
        context = super().get_context_data(**kwargs)
        context.update({
            'shop':shop,
            "form":form,
        })
        return context
    
    
    def form_valid(self, form):
        shop = form.save(commit=False)
        shop.user = self.request.user
        # print(self.kwargs['pk'])
        pbk = shop.rzp_pb_key
        pbk = encrypter.encrypt(pbk.encode())
        shop.rzp_pb_key = pbk

        prk = shop.rzp_pr_key
        prk = encrypter.encrypt(prk.encode())
        shop.rzp_pr_key = prk

        shop.save()
        return super(BankDetailUpdateView, self).form_valid(form)


    



# ******************** PRODUCT VIEWS ****************



class ProductListView(LoginRequiredMixin, ListView):    
    template_name = 'shop/product_list.html'

    def form_valid(self):
        print("\n\n\n\n\nasdkjasdbjhabsdjhbasd\n\n\n\n")
        if self.request.POST.get("q"):
            print("\n\n\n\n",self.request.POST.get("q"))


    def get_queryset(self, **kwargs):
        category = self.kwargs['cat']

        # print(Product.objects.filter(shop__pk = self.kwargs['pk']))
        # queryset.filter(category = category)
        if self.kwargs['cat'] == 0:
            queryset = Product.objects.filter(shop__pk = self.kwargs['pk'])
        else:
            category_item = Category.objects.get(id = category)
            queryset = Product.objects.filter(shop__pk = self.kwargs['pk'])
            queryset = queryset.filter(category = category_item)
        # print(queryset)
        
        
        if self.request.GET.get("q"):
            print("\n\n\n\n",self.request.GET.get("q"), "get")
            queryset = queryset.filter(name__icontains = self.request.GET.get("q"))
            q2 = Product.objects.filter(index__icontains = self.request.GET.get("q"), shop__pk = self.kwargs['pk'])
            print(q2)
            print("final qs: ", queryset)
            queryset = queryset.union(q2)
        # pagination
        p = Paginator(queryset, 10)
        page = self.request.GET.get("page")
        qs = p.get_page(page)

        return qs

    def get_context_data(self, **kwargs):
        shop = Shop.objects.get(id = self.kwargs['pk'])
        form = ProductStockUpdateForm()
        selected_cat_id = self.kwargs["cat"]
        if selected_cat_id != 0:
            curr_category = Category.objects.get(id = selected_cat_id)
            print("asds: ",curr_category)
        else:
            curr_category = "All"
        context = super().get_context_data(**kwargs)
        orders = Order.objects.filter(shop = shop)
        orders = orders.filter(completed = False).count()
        categories = Category.objects.filter(shop = shop)
        cart_items = self.request.user.cart_items()
        # print("cart_items:", cart_items)

        cart_p = self.request.user.cart_prods()
        # print("cart_prods:", cart_p)
        p_ids = [x.id for x in cart_p ]
        # print(p_ids)
        prods = Product.objects.filter(pk__in=p_ids)

        slides = Slide.objects.filter(user = shop.user)

        cart = Item.objects.filter(cart=self.request.user.cart)
        # for i in cart_items:
        #     print(i)
        #     cart_p.append(i.product)
        context.update({
            'shop':shop,
            "form":form,
            "categories":categories,
            "current_category":curr_category,
            "cart_items": cart,
            "prods":prods,
            "orders": orders,
            "slides":slides,
        })

        


        return context
          



class ProductListWholeView(LoginRequiredMixin, ListView):    
    template_name = 'shop/product_list_whole.html'

    def form_valid(self):
        print("\n\n\n\n\nasdkjasdbjhabsdjhbasd\n\n\n\n")
        if self.request.POST.get("q"):
            print("\n\n\n\n",self.request.POST.get("q"))


    def get_queryset(self, **kwargs):
        # category = self.kwargs['cat']

        # print(Product.objects.filter(shop__pk = self.kwargs['pk']))
        # queryset.filter(category = category)
        # if self.kwargs['cat'] == 0:
        #     queryset = Product.objects.filter(shop__pk = self.kwargs['pk'])
        # else:
        #     category_item = Category.objects.get(id = category)
        #     queryset = Product.objects.filter(shop__pk = self.kwargs['pk'])
        #     queryset = queryset.filter(category = category_item)
        # print(queryset)
        queryset = Product.objects.all()
        print("get request data", self.request.GET)
        print("post request data", self.request.POST)
        print("kwargs request data", kwargs)
        print("full path request data", self.request.get_full_path())
        param = self.request.get_full_path()
        param = param.split("/")
        print(param)
        param = param[2]
        print(param)

        # print("the passed get request.: ", kwargs["pk"])
        queryset = queryset.filter(name__icontains = param)
        q2 = Product.objects.filter(index__icontains = param)
        print(q2)
        queryset = queryset.union(q2)

shop/templates/shop/shop/confirm_user.html
{% extends "base.html" %} {% load tailwind_filters %}{% block content %}
<a href = "{% url "base:home" %}">
    <h1 class = "text-3xl font-bold justify-center text-black-300 uppercase text-underline bg-gray-100 px-3 py-3 hover:shadow-lg" style="border-radius:0 0 40px 40px; width:100%; font-family: 'Nunito', sans-serif; transition:0.5s">
        Click here to go back
    </h1>
</a>
<br>
<br>
<br>
<h1 class = "text-5xl font-bold justify-center text-black-300 uppercase text-underline bg-gray-100 px-3 py-3 hover:shadow-lg" style="border-radius:0 0 40px 40px; width:100%; font-family: 'Nunito', sans-serif; transition:0.5s">
  Re-enter your credentials to confirm your identity:
</h1>
<!-- {% csrf_token %} -->
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %} {{ form|crispy }} <button type="submit">Submit</button>
</form>
<h3>{{msg}}</h3>
{% endblock content %}

shop/templates/shop/shop/shop_create.html
{% extends "base.html" %}{% load tailwind_filters %} {% block content %}
{{lab}}

<!-- component -->
<style>
    body {
      background: #e2e8f0;
    }
      *:hover {
        transition: all 150ms ease-in;
      }
</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Hind&family=Nunito&display=swap" rel="stylesheet">


<div class="antialiased w-full mx-auto my-12 bg-gray-300"  style="border-radius:0 0 90px 90px">
    <div class="w-full md:w-1/2 relative z-0 py-0 px-8 bg-black-200 md:px-0 md:py-2 px-4" style="padding-left:20px;padding-right:20px; width:auto">
        
      <h1 class="bg-gray-700 block flex items-center justify-center my-8 p-8 text-4xl font-semibold text-gray-600 uppercase mt-6" style="color:White;border-radius:0 0 40px 40px">
        <span>Enter Shop detail</span>
      </h1>
      <form method="POST" id="update_form"
      enctype="multipart/form-data"
      class = "p-4"
      >
        {% csrf_token %} {{ form|crispy }}
        <button
          class="flex ml-right text-white bg-indigo-500 m-4 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
          type="submit"
        >
          Register Shop
        </button>
      </form>
      </div>
    </div>
  </div>
  
</div>

{% endblock %}

shop/templates/shop/shop/shop_detail_modal.html
{% comment %} <button class="block text-white bg-indigo-600 focus:outline-none font-medium rounded-lg text-sm px-5 py-1 text-center" type="button" data-modal-toggle="defaultModal">
    View Details
</button> {% endcomment %}

<!-- Main modal -->
<div id="defaultModal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">
    <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600">
                <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                    <b>{{shop}}</b> Details:
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="defaultModal">
                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>  
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-6 space-y-6">
                <table class="table-auto text-sm text-white">
                    <tbody>
                      <tr>
                        <td>Name: </td>
                        <td>{{shop.name}}</td>
                      </tr>
                      <tr>
                        <td>category: </td>
                        <td>{{shop.category}}</td>
                      </tr>
                      <tr>
                        <td>Open Time: </td>
                        <td>{{shop.open_time}}</td>
                      </tr>
                      <tr>
                        <td>Close Time: </td>
                        <td>{{shop.close_time}}</td>
                      </tr>
                      <tr>
                        <td>Email: </td>
                        <td>{{shop.email}}</td>
                      </tr>
                      <tr>
                        <td>Phone: </td>
                        <td>{{shop.phone}}</td>
                      </tr>
                      <tr>
                        <td>Address: </td>
                        <td>{{shop.address}}</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
</div>

shop/templates/shop/shop/shop_update.html
{% extends "base.html" %}{% load tailwind_filters %} {% block content %}
{{lab}}

<!-- component -->
<style>
    body {
      background: #e2e8f0;
    }
      *:hover {
        transition: all 150ms ease-in;
      }
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hind&family=Nunito&display=swap" rel="stylesheet">
    <div class="antialiased ma  x-w-6xl mx-auto my-12 bg-gray-300"  style="border-radius:0 0 90px 90px">
    <h1 class = "text-5xl justify-center text-black-300 uppercase text-underline bg-gray-100 px-3 py-3 hover:shadow-lg" style="border-radius:0 0 40px 40px; width:100%; font-family: 'Nunito', sans-serif;padding-left:40%; transition:0.5s" >{{shop.name}}</h1>
      
    
      <div class="relative block md:flex items-center" style="margin:20px">
        <div class="w-full md:w-1/2 relative z-1 bg-gray-100 rounded shadow-lg overflow-hidden">
          {% comment %} <div class="text-lg font-medium text-green-500 uppercase p-8 text-center border-b border-gray-200 tracking-wide">Pay as you go</div> {% endcomment %}
          <img
            alt="ecommerce"
            class="object-cover object-center w-full h-full block"
            src="/{{shop.pfp}}"
            height = "100px"
          />
          <div class="block sm:flex md:block lg:flex items-center justify-center">
            <div class="mt-8 sm:m-8 md:m-0 md:mt-8 lg:m-8 text-center">
              <div class="inline-flex items-center">
                <span class="text-3xl font-medium">{{order_num}}</span>
              </div>
              <span class="block text-sm text-gray-600 mt-2">Total Orders</span>
            </div>
            <div class="mt-4 mb-8 sm:m-8 md:m-0 md:mt-4 md:mb-8 lg:m-8 text-center">
              <div class="inline-flex items-center">
                <span class="text-3xl font-medium">₹ {{total_sales}}</span>
              </div>
              <span class="block text-sm text-gray-600 mt-2">Total Sales</span>
            </div>
          </div>
          <div class="flex justify-center mt-3 py-4">
            
            <ul>
              <li class="flex items-center">
                <div class="bg-green-200 rounded-full p-2 fill-current text-green-700">
                  <svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="icon-umbrella"><path class="primary" d="M11 3.05V2a1 1 0 0 1 2 0v1.05A10 10 0 0 1 22 13c0 1.33-2 1.33-2 0a2 2 0 1 0-4 0c0 1.33-2 1.33-2 0a2 2 0 1 0-4 0c0 1.33-2 1.33-2 0a2 2 0 1 0-4 0c0 1.33-2 1.33-2 0a10 10 0 0 1 9-9.95z"/><path class="secondary" d="M11 14a1 1 0 0 1 2 0v5a3 3 0 0 1-6 0 1 1 0 0 1 2 0 1 1 0 0 0 2 0v-5z"/></svg>
                </div>
                <span class="text-gray-700 text-lg ml-3"><em>{{shop.products.all.count}}</em> Products in shop</span>
              </li>
              <li class="flex items-center mt-3">
                <div class="bg-green-200 rounded-full p-2 fill-current text-green-700">
                  <svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="icon-shopping-bag"><path class="primary" d="M5 8h14a1 1 0 0 1 1 .92l1 12A1 1 0 0 1 20 22H4a1 1 0 0 1-1-1.08l1-12A1 1 0 0 1 5 8z"/><path class="secondary" d="M9 10a1 1 0 0 1-2 0V7a5 5 0 1 1 10 0v3a1 1 0 0 1-2 0V7a3 3 0 0 0-6 0v3z"/></svg>
                </div>
                <span class="text-gray-700 text-lg ml-3"><em>{{shop.suppliers.all.count}}</em> Suppliers</span>
              </li>
            </ul>
          </div>
        </div>
        <div class="w-full md:w-1/2 relative z-0 px-8 bg-black-200 md:px-0 md:py-16 px-4" style="padding-left:20px">
            
          <h1 class="block flex items-center justify-center p-8 text-4xl bg-gray-400 rounded font-semibold text-gray-800 uppercase mt-16" style="color:White">
            <span>Update Shop detail</span>
          </h1>
          <form method="POST" id="update_form"
          enctype="multipart/form-data" style="padding-left:20px"
          >
            {% csrf_token %} {{ form|crispy }}
            <button
              class="flex ml-right text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
              type="submit"
            >
              Update
            </button>
          </form>
          <a href = "{% url "shop:confirm-user" %}">
            <button
              class="flex ml-right text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded my-4 float-right -my-10"
              type="submit"
            >
              Update Bank Details
            </button>
          </a>
          </div>
        </div>
      </div>
        
      
    </div>



{{cat}}

{{cat.products.all}}
{{objects_list}} 

<script>
    phone_f = document.getElementById("phone_field")
    console.log(phone_f)
    console.log(typeof(phone_f.value))
</script>
{% endblock %}

shop/templates/shop/shop/update_bank_details.html
{% extends "base.html" %} {% load tailwind_filters %}{% block content %}
<a href = "{% url "base:home" %}">
    <h1 class = "text-3xl font-bold justify-center text-black-300 uppercase text-underline bg-gray-100 px-3 py-3 hover:shadow-lg" style="border-radius:0 0 40px 40px; width:100%; font-family: 'Nunito', sans-serif; transition:0.5s">
        Click here to go back
    </h1>
</a>
<h1 class = "text-5xl font-bold justify-center text-black-300 uppercase text-underline bg-gray-100 px-3 py-3 hover:shadow-lg" style="border-radius:0 0 40px 40px; width:100%; font-family: 'Nunito', sans-serif; transition:0.5s">
  Update Bank details:
</h1>
<!-- {% csrf_token %} -->
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %} {{ form|crispy }} <button type="submit">Submit</button>
</form>
<h3>{{msg}}</h3>
{% endblock content %}