base/urls.py
from django.contrib import admin
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.HomeView.as_view(), name = 'home'),
    # path('leads_list', views.LeadListView.as_view(), name = 'leads_list'),
    # path('create', views.LeadCreateView.as_view(), name = "lead_create"),
    # path('detail/<int:pk>', views.LeadDetailView.as_view(), name = 'lead_detail'),
    # path('lead_update/<int:pk>', views.LeadUpdateView.as_view(), name = 'lead_update'),
    # path('lead_delete/<int:pk>', views.LeadDeleteView.as_view(), name = 'lead_delete'),
    # path('assign_agent/<int:pk>', views.AssignAgentView.as_view(), name = "assign_agent"),
    # path('category_update/<int:pk>', views.LeadCategoryUpdateView.as_view(), name = "category_update"),
    # path('category_list', views.CategoryListView.as_view(), name = 'category_list'),
    
    # path('category_detail/<int:pk>', views.CategoryDetailView.as_view(), name = 'category_detail'),

]

shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views

app_name = 'shop' 

urlpatterns = [
    # products
    path('<int:pk>/<int:cat>', views.ProductListView.as_view(), name = 'home'),
    path('<int:pk>/create', views.ProductCreateView.as_view(), name = "product_create"),
    path('delete/<int:pk>', views.ProductDeleteView.as_view(), name = "product_delete"),
    path('update/<int:pk>', views.ProductUpdateView.as_view(), name = "product_update"),
    path('compare/<int:pk>', views.ProductCompareView.as_view(), name = "product_compare"),
    path('<pk>/all', views.ProductListWholeView.as_view(), name = "product_all"),
    
    
    # others
    path('item-create/<int:pk>', views.ItemCreateView.as_view(), name = 'item-create'),
    path('item-update/<int:pk>', views.ItemUpdateView.as_view(), name = 'item-update'),
    path('item-delete/<int:pk>', views.ItemDeleteView.as_view(), name = 'item-delete'),
    path('order-create/<int:pk>', views.OrderCreateView.as_view(), name = 'order-create'),
    path('order-list/<int:pk>', views.OrderListView.as_view(), name = 'order-list'),
    path('order-list-customer/<int:pk>', views.OrderListCustomerView.as_view(), name = 'order-list-customer'),
    path('order-update/<int:pk>', views.OrderUpdateView.as_view(), name = 'order-update'),
    path('order-delete/<int:pk>', views.OrderDeleteView.as_view(), name = 'order-delete'),
    path('order-detail-customer/<int:pk>', views.OrderDetailViewCustomer, name = 'order-detail-customer'),
    path('stock-update/<int:pk>', views.StockUpdateView, name = 'stock-update'),
    path('map-index', views.map_index, name = 'map-index'),


    # categories
    path('<int:pk>/categories', views.category_create, name = 'categories'),
    path('category-delete/<int:pk>', views.category_delete, name = 'category-delete'),
    path('category-detail/<int:pk>', views.CategoryDetailView.as_view(), name = 'category-detail'),


    # suppliers
    path('<int:pk>/suppliers', views.supplier_create, name = 'suppliers'),
    path('supplier-update/<int:pk>', views.SupplierUpdateView.as_view(), name = 'supplier-update'),
    path('supplier-delete/<int:pk>', views.supplier_delete, name = 'supplier-delete'),
    path('supplier-detail/<int:pk>', views.SupplierDetailView.as_view(), name = 'supplier-detail'),

    # slides
    path('slide-create/<int:pk>', views.SlideCreateView.as_view(), name = 'slide-create'),
    path('slide-list/<int:pk>', views.SlideListView.as_view(), name = 'slide-list'),
    path('slide-delete/<int:pk>', views.SlideDeleteView, name = 'slide-delete'),

    # shop
    path('shop-update/<int:pk>', views.ShopUpdateView.as_view(), name = 'shop-update'),
    path('shop-confirm-user', views.confirm_user_view, name = 'confirm-user'),
    path('update-bank-detail/<int:pk>', views.BankDetailUpdateView.as_view(), name = 'update-bank'),

]

smart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
        LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, 
        PasswordResetConfirmView, PasswordResetCompleteView, 
    )
from base.views import SignupView, ProfileDetailView, CartView ,CheckoutDetailView, ProfileUpdateView
from shop.views import payment_handler_with_order_id, success, CheckoutDetailView, payment_handler, ShopCreateView
# from leads.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace = 'base')),
    path('shop/', include('shop.urls', namespace = 'shop')),
    path('login/', LoginView.as_view(),name = 'login'),
    path('logout/', LogoutView.as_view(),name = 'logout'),
    path('profile/<int:pk>', ProfileDetailView.as_view(),name = 'profile'),
    path('profile-update/<int:pk>', ProfileUpdateView.as_view(),name = 'profile-update'),
    path('cart/<int:pk>', CartView,name = 'cart'),
    # path('checkout/<int:pk>', CheckoutDetailView,name = 'checkout'),
    path('checkout/<int:pk>', CheckoutDetailView.as_view(),name = 'checkout'),
    path('signup/', SignupView.as_view(),name = 'signup'),
    # path('password_reset/', PasswordResetView.as_view(),name = 'password_reset'),
    # path('payment/<int:pk>', payment_handler_with_order_id, name = 'payment'),
    path('payment/<int:pk>', payment_handler, name = 'payment'),
    path('success', success, name = 'success-payment'),
    path('password_reset/', PasswordResetView.as_view(),name = 'password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(),name = 'password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name = 'password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(),name = 'password_reset_complete'),

    # shop views
    path("shop_create", ShopCreateView.as_view(), name="shop-create")
    
]

base/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MaxValueValidator, MinValueValidator 

# Create your models here.




class User(AbstractUser):
    pfp = models.ImageField(upload_to = 'static/users', blank = True, null = True)
    address = models.CharField(max_length=100, blank = True, null = True)
    phone = models.BigIntegerField(null = True, blank = True, unique = True)
    email = models.CharField(max_length=50, blank = True, null = True)


    
    def cart_items(self):
        cart_items = {}
        # print(cart_items[[str(a).split(" ")[0]] = a.quantity for a in self.cart.items.all()])
        for a in self.cart.items.all():
            cart_items[str(a).split(" ")[0]] = a.quantity
        print(cart_items)
        return cart_items
    def cart_prods(self):
        cart_items = []
        # print(cart_items[[str(a).split(" ")[0]] = a.quantity for a in self.cart.items.all()])
        for a in self.cart.items.all():
            cart_items.append(a.product)
        print(cart_items)
        return cart_items


class Shop(models.Model):
    cat_choices = (
        ('General', 'GEN'),
        ('Dairy', 'DRY'),
        ('Bakery', 'BKR'),
    )

    name = models.CharField(max_length=50)
    pfp = models.ImageField(upload_to = 'static/shops', blank = True, null = True)
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null = True, blank = True, related_name = "shop")
    category = models.CharField(choices = cat_choices,max_length= 100)
    
    open_time = models.TimeField()
    close_time = models.TimeField()
    phone = models.BigIntegerField(null = True, blank = True, unique = True)
    email = models.EmailField(null = True, blank = True, unique = True)

    address = models.CharField(max_length=200, null=True, blank=True) 

    rzp_pr_key = models.CharField(max_length=400, default = "omFNDCkZBgjorzpFzNNmfKyd") 
    rzp_pb_key = models.CharField(max_length=400, default = "rzp_test_0ovBWEVK2aFRht")


    def __str__(self):
        return self.name



class Notifications(models.Model):
    description = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank = True, null = True)

base/forms.py
from django import forms
from .models import User, Shop
from shop.models import Order
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model
from phonenumber_field.formfields import PhoneNumberField

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', "email", "phone", 'pfp', 'address')
        # field_classes = {'username': UsernameField}

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        self.fields['phone'].widget = forms.TextInput(attrs={
            'id': 'phone_field',
            "min":"1000000000",
            "max":"9999999999",
            "type":"number",
            })
        self.fields['email'].widget = forms.TextInput(attrs={"type":"email"})



class ConfirmUserForm(forms.Form):
    # class Meta:
    #     model = User
    #     fields = ('username', "Password")
        
    #     # field_classes = {'username': UsernameField}
    
    # def __init__(self, *args, **kwargs):
    #     super(ConfirmUserForm, self).__init__(*args, **kwargs)
        
    #     self.fields['password'].widget = forms.PasswordInput()
    username = forms.CharField(initial = "")
    password = forms.CharField(widget=forms.PasswordInput(), initial = "")

class UpdateBankDetailsForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ('rzp_pr_key', "rzp_pb_key")
        
        # field_classes = {'username': UsernameField}
    
    def __init__(self, *args, **kwargs):
        super(UpdateBankDetailsForm, self).__init__(*args, **kwargs)
        
        self.fields['rzp_pr_key'].label = "Razorpay Private Key"
        self.fields['rzp_pb_key'].label = "Razorpay Public Key"




class ShopCreateForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ('name', "category", "pfp", "open_time", "close_time", "phone", "email", "address","rzp_pr_key", "rzp_pb_key")
        
    def __init__(self, *args, **kwargs):
        super(ShopCreateForm, self).__init__(*args, **kwargs)
        self.fields['close_time'].widget = forms.DateInput(attrs={'class':'timepicker'})
        self.fields['rzp_pr_key'].label = "Enter Razorpay Public Key"
        self.fields['rzp_pb_key'].label = "Enter Razorpay Private Key"
        self.fields['rzp_pr_key'].widget = forms.PasswordInput( )
        self.fields['rzp_pb_key'].widget = forms.PasswordInput()
        self.fields['rzp_pb_key'].initial = ""
        self.fields['rzp_pr_key'].initial = ""

        self.fields['phone'].widget = forms.TextInput(attrs={
            'id': 'phone_field',
            "min":"1000000000",
            "max":"9999999999",
            "type":"number",
            })
        self.fields['email'].widget = forms.TextInput(attrs={"type":"email"})





class ShopUpdateForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ('name', "pfp", "open_time", "close_time", "phone", "email", "address")
        # widgets = {
        #     'phone':PhoneNumberField()
            # "open_time":forms.TimeField(),
            # "close_time":forms.TimeField(),
        # }
    def __init__(self, *args, **kwargs):
        super(ShopUpdateForm, self).__init__(*args, **kwargs)
        self.fields['phone'].widget = forms.TextInput(attrs={
            'id': 'phone_field',
            "min":"1000000000",
            "max":"9999999999",
            "type":"number",
            })
        self.fields['email'].widget = forms.TextInput(attrs={"type":"email"})



class CustomUserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', "email", "phone", 'pfp', 'address')
        # field_classes = {'username': UsernameField}
        



class OrderCreateForm(forms.Form):
    class Meta:
        model = Order
        fields = ('address', 'description', )

base/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from .models import Shop, User
from shop.models import Item, Cart, Slide
# from .forms import LeadForm, LeadModelForm, CustomUserCreationForm, AssignAgentForm, LeadCategoryUpdateForm
from .forms import CustomUserCreationForm, CustomUserUpdateForm
from django.shortcuts import redirect, reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
# from agents.mixins import OrganiserLoginRequiredMixin

# Create your views here.


class HomeView(LoginRequiredMixin, ListView):
    template_name = 'base/shop_list.html'

    def get_context_data(self, **kwargs):
        superusers = User.objects.get(is_superuser=True)
        context = super().get_context_data(**kwargs)
        slides = Slide.objects.filter(user = superusers)
        sl1 = Slide.objects.first()
        context.update({
            'slides':slides,
            'sl':sl1,
            "hello":"asdasdsadsad"
            # 'categories':prod.get_categories()
        })
        return context
    
    def form_valid(self, **kwargs):
        print(self)
        print(kwargs)
        print("\n\n\n\n\nasdkjasdbjhabsdjhbasd\n\n\n\n")
        if self.request.GET.get("q"):
            print("\n\n\n\n",self.request.POST.get("q"))

    def get(self, *args, **kwargs):
        pass


    def get_queryset(self, **kwargs):
        queryset = Shop.objects.all()
        return queryset
    


    def get(self, *args, **kwargs):
        try:
            if self.request.user.shop:
                return redirect('shop:home', pk=self.request.user.shop.id, cat=0)
        except:
            if self.request.GET:
                print(self.request.GET.get("q"))
                return redirect("shop:product_all", pk = self.request.GET.get("q"))
            return super(HomeView, self).get(*args, **kwargs)
            # return super(HomeView, self).get(*args, **kwargs)



class SignupView(CreateView):
    template_name = "registration/user_create.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")



class ProfileDetailView(LoginRequiredMixin, DetailView):
    template_name = 'registration/user_detail.html'
    context_object_name = 'user'


    def get_queryset(self):
        return User.objects.all()




class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'registration/user_detail.html'
    context_object_name = 'user'


    def get_queryset(self):
        return User.objects.all()



class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'registration/user_update.html'
    form_class = CustomUserUpdateForm

    
    def get_context_data(self, **kwargs):
        curr_supp = User.objects.get(id = self.kwargs["pk"])
        form = CustomUserUpdateForm(instance = curr_supp)
        # supp_id = self.kwargs['pk']
        
        # supp = Supplier.objects.get(id = supp_id)
        # print(prod)
        # queryset = Supplier.objects.get(id = supp_id)
        context = super().get_context_data(**kwargs)
        context.update({
            'supplier':curr_supp,
            # 'categories':prod.get_categories()
        })
        print(curr_supp)
        return context
    
    
    def get_queryset(self): 
        user = self.request.user
        # supp_id = self.kwargs["pk"]

        # supp = Supplier.objects.get(id= supp_id)
        queryset = User.objects.filter(id = user.id)
        return queryset

    
    def get_success_url(self):
        return reverse('profile', kwargs = {'pk': self.kwargs['pk']})



def CartView(request, pk):
    msg = ''
    user = request.user
    print(user)
    shops = Shop.objects.all()
    items = request.user.cart.items.all()
    total = {}
    shops = set()
    for i in items:
        shops.add(i.product.shop)
        # if str(i.product.shop.id) in  total:
        if i.product.shop.id in  total:
            # total[str(i.product.shop.id)] += i.product.price * i.quantity
            total[i.product.shop.id] += i.product.price * i.quantity

        else:
            # total[str(i.product.shop.id)] = i.product.price * i.quantity
            total[i.product.shop.id] = i.product.price * i.quantity

    print(total)
    context = {'msg':msg, 'items': items, 'shops': shops, 'total':total}
    return render(request , 'base/cart.html', context)





def CheckoutDetailView(req, pk):

    return HttpResponse("asdadas")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>

    {% comment %}
    <script src="static//prod_list.js"></script>
    {% endcomment %} {% comment %}
    <script src="https://unpkg.com/flowbite@1.3.4/dist/flowbite.js"></script>

    {% endcomment %}
    <link
      rel="stylesheet"
      href="https://unpkg.com/flowbite@1.3.4/dist/flowbite.min.css"
    />
    <link
      rel="stylesheet"
      href="https://unpkg.com/flowbite@1.3.4/dist/flowbite.min.css"
    />
    <link
      rel="stylesheet"
      href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
    />
    <script src="https://unpkg.com/flowbite@1.3.4/dist/flowbite.js"></script>
    {% comment %} <script src="./TW-ELEMENTS-PATH/dist/js/index.min.js"></script> {% endcomment %}
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <style>
      body {
        width: 95%;
        align-self: auto;
        align-items: center;
        align-content: center;
        padding-left: 3%;
        padding-right: 3%;
        padding-bottom: 0%;
        background: #e6e3e3;
        margin-bottom:50px
        margin-left:20%;
        height:100%;
      }
      .container {
        max-width: 50%;
        border-bottom: 10px;
      }
    </style>
    <title>ShopEasy</title>
  </head>
  <body>
    <div style="display:block; margin-bottom:0px; padding-bottom: 0px">
      <div>
        <div class="container" style="display:flex; padding-bottom:20px">
          <div class="px-0">
          {% if request.user == shop.user %}
          {% include "sidebar.html" %}
          {% comment %} <a href = "{% url 'shop:shop-update' shop.id %}"> Update Shop Details </a> {% endcomment %}
          
          {% else %}
          {% endif %}
          </div>
          {% if request.user.shop %}
          <div class="container px-10" style="width:80%; align:right; margin-left:20%">
          {% else %}
          <div class="container">
          {% endif %}

          {% include "navbar.html" %} 
          {% block content %} {% endblock content %}
          </div>
        </div>
      </div>
      
    </div>
  </body>
  {% comment %} <script type="text/javascript">
    console.log("working")
    var btn_carousel = document.querySelector('#carousel-next-slide-btn')
    console.log(btn_carousel)
    btn_carousel.click()
    setTimeout(btn_carousel.click(),1000);
  
  
  </script> {% endcomment %}

  {% comment %} <script src="themes/js/jquery.js" type="text/javascript"></script>
  <script src="themes/js/bootstrap.min.js" type="text/javascript"></script>
  <script src="themes/js/google-code-prettify/prettify.js"></script>

  <script src="themes/js/bootshop.js"></script>
  <script src="themes/js/jquery.lightbox-0.5.js"></script> {% endcomment %}


</html>

templates/sidebar.html
<aside class="w-64" aria-label="Sidebar" style="height:100vh; position:fixed; top:0; left:0; overflow-x:hidden;">
<div class="overflow-y-auto py-4 px-3 bg-gray-50 rounded dark:bg-gray-800" style="height:100%">
<ul class="space-y-2">
<li>
<a href="{% url 'shop:shop-update' shop.id %}" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
<svg class="w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
<span class="ml-3">Shop Details</span>
</a>
</li>
<li>
<a href="{% url 'shop:suppliers' pk=request.user.shop.id %}" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
<svg class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
<span class="flex-1 ml-3 whitespace-nowrap">Supplier</span>
</a>
</li>
<li>
<a href="{% url 'shop:categories' shop.id %}" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
<svg class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"></path></svg>
<span class="flex-1 ml-3 whitespace-nowrap">Categories</span>
{% comment %} <span class="inline-flex justify-center items-center p-3 ml-3 w-3 h-3 text-sm font-medium text-blue-600 bg-blue-200 rounded-full dark:bg-blue-900 dark:text-blue-200">{{categories.count}}</span> {% endcomment %}
</a>
</li>
<li>
<a href="{% url 'shop:order-list' shop.pk %}" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
<svg class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 2a4 4 0 00-4 4v1H5a1 1 0 00-.994.89l-1 9A1 1 0 004 18h12a1 1 0 00.994-1.11l-1-9A1 1 0 0015 7h-1V6a4 4 0 00-4-4zm2 5V6a2 2 0 10-4 0v1h4zm-6 3a1 1 0 112 0 1 1 0 01-2 0zm7-1a1 1 0 100 2 1 1 0 000-2z" clip-rule="evenodd"></path></svg>
<span class="flex-1 ml-3 whitespace-nowrap">Orders </span>
{% if orders > 0 %}
        <span class="inline-block py-1 px-1.5 leading-none text-center whitespace-nowrap align-baseline font-bold bg-red-600 text-white rounded ml-2">{{orders}} </span>
{% else %}
{% endif %}
</a>
</li>
<li>
<a href="{% url 'shop:product_create' shop.id %}" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
<svg class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M8.707 7.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l2-2a1 1 0 00-1.414-1.414L11 7.586V3a1 1 0 10-2 0v4.586l-.293-.293z"></path><path d="M3 5a2 2 0 012-2h1a1 1 0 010 2H5v7h2l1 2h4l1-2h2V5h-1a1 1 0 110-2h1a2 2 0 012 2v10a2 2 0 01-2 2H5a2 2 0 01-2-2V5z"></path></svg>
<span class="flex-1 ml-3 whitespace-nowrap">Add Product</span>
</a>
</li>
<li>
<a href="{% url 'shop:slide-create' pk=request.user.id %}" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
<svg class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 4a3 3 0 00-3 3v6a3 3 0 003 3h10a3 3 0 003-3V7a3 3 0 00-3-3H5zm-1 9v-1h5v2H5a1 1 0 01-1-1zm7 1h4a1 1 0 001-1v-1h-5v2zm0-4h5V8h-5v2zM9 8H4v2h5V8z" clip-rule="evenodd"></path></svg>
<span class="flex-1 ml-3 whitespace-nowrap">Manage Slides</span>
</a>
</li>
<li>
<a href="/logout" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">

<svg class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 3a1 1 0 00-1 1v12a1 1 0 102 0V4a1 1 0 00-1-1zm10.293 9.293a1 1 0 001.414 1.414l3-3a1 1 0 000-1.414l-3-3a1 1 0 10-1.414 1.414L14.586 9H7a1 1 0 100 2h7.586l-1.293 1.293z" clip-rule="evenodd"></path></svg>
<span class="flex-1 ml-3 whitespace-nowrap">Logout</span>
</a>
</li>
</ul>
</div>
</aside>

templates/stylesNscripts.html
<script>
  console.log("Hello");
</script>