base/urls.py
from django.contrib import admin
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.HomeView.as_view(), name = 'home'),
    # path('leads_list', views.LeadListView.as_view(), name = 'leads_list'),
    # path('create', views.LeadCreateView.as_view(), name = "lead_create"),
    # path('detail/<int:pk>', views.LeadDetailView.as_view(), name = 'lead_detail'),
    # path('lead_update/<int:pk>', views.LeadUpdateView.as_view(), name = 'lead_update'),
    # path('lead_delete/<int:pk>', views.LeadDeleteView.as_view(), name = 'lead_delete'),
    # path('assign_agent/<int:pk>', views.AssignAgentView.as_view(), name = "assign_agent"),
    # path('category_update/<int:pk>', views.LeadCategoryUpdateView.as_view(), name = "category_update"),
    # path('category_list', views.CategoryListView.as_view(), name = 'category_list'),
    
    # path('category_detail/<int:pk>', views.CategoryDetailView.as_view(), name = 'category_detail'),

]

shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views

app_name = 'shop' 

urlpatterns = [
    # products
    path('<int:pk>/<int:cat>', views.ProductListView.as_view(), name = 'home'),
    path('<int:pk>/create', views.ProductCreateView.as_view(), name = "product_create"),
    path('delete/<int:pk>', views.ProductDeleteView.as_view(), name = "product_delete"),
    path('update/<int:pk>', views.ProductUpdateView.as_view(), name = "product_update"),
    path('compare/<int:pk>', views.ProductCompareView.as_view(), name = "product_compare"),
    path('<pk>/all', views.ProductListWholeView.as_view(), name = "product_all"),
    
    
    # others
    path('item-create/<int:pk>', views.ItemCreateView.as_view(), name = 'item-create'),
    path('item-update/<int:pk>', views.ItemUpdateView.as_view(), name = 'item-update'),
    path('item-delete/<int:pk>', views.ItemDeleteView.as_view(), name = 'item-delete'),
    path('order-create/<int:pk>', views.OrderCreateView.as_view(), name = 'order-create'),
    path('order-list/<int:pk>', views.OrderListView.as_view(), name = 'order-list'),
    path('order-list-customer/<int:pk>', views.OrderListCustomerView.as_view(), name = 'order-list-customer'),
    path('order-update/<int:pk>', views.OrderUpdateView.as_view(), name = 'order-update'),
    path('order-delete/<int:pk>', views.OrderDeleteView.as_view(), name = 'order-delete'),
    path('order-detail-customer/<int:pk>', views.OrderDetailViewCustomer, name = 'order-detail-customer'),
    path('stock-update/<int:pk>', views.StockUpdateView, name = 'stock-update'),
    path('map-index', views.map_index, name = 'map-index'),


    # categories
    path('<int:pk>/categories', views.category_create, name = 'categories'),
    path('category-delete/<int:pk>', views.category_delete, name = 'category-delete'),
    path('category-detail/<int:pk>', views.CategoryDetailView.as_view(), name = 'category-detail'),


    # suppliers
    path('<int:pk>/suppliers', views.supplier_create, name = 'suppliers'),
    path('supplier-update/<int:pk>', views.SupplierUpdateView.as_view(), name = 'supplier-update'),
    path('supplier-delete/<int:pk>', views.supplier_delete, name = 'supplier-delete'),
    path('supplier-detail/<int:pk>', views.SupplierDetailView.as_view(), name = 'supplier-detail'),

    # slides
    path('slide-create/<int:pk>', views.SlideCreateView.as_view(), name = 'slide-create'),
    path('slide-list/<int:pk>', views.SlideListView.as_view(), name = 'slide-list'),
    path('slide-delete/<int:pk>', views.SlideDeleteView, name = 'slide-delete'),

    # shop
    path('shop-update/<int:pk>', views.ShopUpdateView.as_view(), name = 'shop-update'),
    path('shop-confirm-user', views.confirm_user_view, name = 'confirm-user'),
    path('update-bank-detail/<int:pk>', views.BankDetailUpdateView.as_view(), name = 'update-bank'),

]

smart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
        LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, 
        PasswordResetConfirmView, PasswordResetCompleteView, 
    )
from base.views import SignupView, ProfileDetailView, CartView ,CheckoutDetailView, ProfileUpdateView
from shop.views import payment_handler_with_order_id, success, CheckoutDetailView, payment_handler, ShopCreateView
# from leads.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace = 'base')),
    path('shop/', include('shop.urls', namespace = 'shop')),
    path('login/', LoginView.as_view(),name = 'login'),
    path('logout/', LogoutView.as_view(),name = 'logout'),
    path('profile/<int:pk>', ProfileDetailView.as_view(),name = 'profile'),
    path('profile-update/<int:pk>', ProfileUpdateView.as_view(),name = 'profile-update'),
    path('cart/<int:pk>', CartView,name = 'cart'),
    # path('checkout/<int:pk>', CheckoutDetailView,name = 'checkout'),
    path('checkout/<int:pk>', CheckoutDetailView.as_view(),name = 'checkout'),
    path('signup/', SignupView.as_view(),name = 'signup'),
    # path('password_reset/', PasswordResetView.as_view(),name = 'password_reset'),
    # path('payment/<int:pk>', payment_handler_with_order_id, name = 'payment'),
    path('payment/<int:pk>', payment_handler, name = 'payment'),
    path('success', success, name = 'success-payment'),
    path('password_reset/', PasswordResetView.as_view(),name = 'password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(),name = 'password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name = 'password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(),name = 'password_reset_complete'),

    # shop views
    path("shop_create", ShopCreateView.as_view(), name="shop-create")
    
]

shop/views.py
from urllib import request
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import (
                        ProductModelForm, ProductStockUpdateForm, 
                        CategoryModelForm, ItemModelForm, OrderModelForm, 
                        OrderUpdateModelForm, StockUpdateForm,
                        SlideModelForm, SupplierModelForm, SupplierUpdateForm,
                    )
from django.shortcuts import redirect, reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from base.models import Shop, User
from .models import Product, Category, OrderItem, Order, Cart, StockFile, Item, Slide, Supplier
import razorpay
from django.views.decorators.csrf import csrf_exempt
import pandas as pd
import os
from base.forms import ShopUpdateForm, ShopCreateForm, ConfirmUserForm, UpdateBankDetailsForm
from django.db.models import Sum



from django.core.paginator import Paginator
import folium
import geocoder as gc
from django.contrib.auth.models import auth
from cryptography.fernet import Fernet
# Create your views here.



encryption_key = b"zdeU8DTcUCwtACFlKKwh1lGMOq1i6wd3YmOFduJsfbk="
encrypter = Fernet(encryption_key)


# ******************* SHOP VIEWS ********************


class ShopUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'shop/shop/shop_update.html'
    form_class = ShopUpdateForm
    def get_success_url(self):
        # print(self.object.product.shop)
        # print("asdsadasd")

        return reverse('shop:shop-update', kwargs = {'pk': self.request.user.shop.id})

    def get_queryset(self):
        queryset =Shop.objects.filter(id=self.kwargs['pk'])
        print("inside  get_queryset()")
        print(queryset)
        return queryset
    
    def get_context_data(self, **kwargs):
        shop = Shop.objects.get(id = self.kwargs['pk'])
        form = ShopUpdateForm(instance = shop)
        orders = Order.objects.filter(shop=shop)
        total_sales = Order.objects.filter(shop=shop).aggregate(Sum('price'))
        context = super().get_context_data(**kwargs)
        context.update({
            'shop':shop,
            "form":form,
            "total_sales":total_sales["price__sum"] if total_sales["price__sum"] else 0,
            "order_num":len(orders)
        })
        
        return context
    

class ShopCreateView(LoginRequiredMixin, CreateView):
    template_name = 'shop/shop/shop_create.html'
    form_class = ShopCreateForm
    def get_success_url(self):
        print(self.kwargs) 
        return reverse('shop:home', kwargs = {'pk': self.object.id, 'cat':0})

    def form_valid(self, form):
        shop = form.save(commit=False)
        shop.user = self.request.user
        # print(self.kwargs['pk'])
        pbk = shop.rzp_pb_key
        pbk = encrypter.encrypt(pbk.encode())
        shop.rzp_pb_key = pbk

        prk = shop.rzp_pr_key
        prk = encrypter.encrypt(prk.encode())
        shop.rzp_pr_key = prk

        shop.save()
        return super(ShopCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ShopCreateView, self).get_form_kwargs()
        # kwargs.update({'user': self.request.user})
        return kwargs



class ShopView(LoginRequiredMixin, ListView):
    template_name = 'shop/product_list.html'


def confirm_user_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = None
        user = auth.authenticate(username = username, password = password)
        if user:
            if user==request.user:
                return redirect("shop:update-bank", pk=request.user.shop.id)
            else:
                return HttpResponse("You are not the owner of this shop. Please go back and login as the owner.")
        else:
            return HttpResponse("Authentication Failed. Please go back and try again.")


    else:
        form = ConfirmUserForm()
        return render(request, "shop/shop/confirm_user.html", {"form":form})



class BankDetailUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'shop/shop/update_bank_details.html'
    form_class = UpdateBankDetailsForm
    def get_success_url(self):
        # print(self.object.product.shop)
        # print("asdsadasd")

        return reverse('shop:shop-update', kwargs = {'pk': self.request.user.shop.id})

    def get_queryset(self):
        queryset =Shop.objects.filter(id=self.kwargs['pk'])
        print("inside  get_queryset()")
        print(queryset)
        return queryset
    
    def get_context_data(self, **kwargs):
        shop = Shop.objects.get(id = self.kwargs['pk'])
        form = UpdateBankDetailsForm(instance = shop)
        context = super().get_context_data(**kwargs)
        context.update({
            'shop':shop,
            "form":form,
        })
        return context
    
    
    def form_valid(self, form):
        shop = form.save(commit=False)
        shop.user = self.request.user
        # print(self.kwargs['pk'])
        pbk = shop.rzp_pb_key
        pbk = encrypter.encrypt(pbk.encode())
        shop.rzp_pb_key = pbk

        prk = shop.rzp_pr_key
        prk = encrypter.encrypt(prk.encode())
        shop.rzp_pr_key = prk

        shop.save()
        return super(BankDetailUpdateView, self).form_valid(form)


    



# ******************** PRODUCT VIEWS ****************



class ProductListView(LoginRequiredMixin, ListView):    
    template_name = 'shop/product_list.html'

    def form_valid(self):
        print("\n\n\n\n\nasdkjasdbjhabsdjhbasd\n\n\n\n")
        if self.request.POST.get("q"):
            print("\n\n\n\n",self.request.POST.get("q"))


    def get_queryset(self, **kwargs):
        category = self.kwargs['cat']

        # print(Product.objects.filter(shop__pk = self.kwargs['pk']))
        # queryset.filter(category = category)
        if self.kwargs['cat'] == 0:
            queryset = Product.objects.filter(shop__pk = self.kwargs['pk'])
        else:
            category_item = Category.objects.get(id = category)
            queryset = Product.objects.filter(shop__pk = self.kwargs['pk'])
            queryset = queryset.filter(category = category_item)
        # print(queryset)
        
        
        if self.request.GET.get("q"):
            print("\n\n\n\n",self.request.GET.get("q"), "get")
            queryset = queryset.filter(name__icontains = self.request.GET.get("q"))
            q2 = Product.objects.filter(index__icontains = self.request.GET.get("q"), shop__pk = self.kwargs['pk'])
            print(q2)
            print("final qs: ", queryset)
            queryset = queryset.union(q2)
        # pagination
        p = Paginator(queryset, 10)
        page = self.request.GET.get("page")
        qs = p.get_page(page)

        return qs

    def get_context_data(self, **kwargs):
        shop = Shop.objects.get(id = self.kwargs['pk'])
        form = ProductStockUpdateForm()
        selected_cat_id = self.kwargs["cat"]
        if selected_cat_id != 0:
            curr_category = Category.objects.get(id = selected_cat_id)
            print("asds: ",curr_category)
        else:
            curr_category = "All"
        context = super().get_context_data(**kwargs)
        orders = Order.objects.filter(shop = shop)
        orders = orders.filter(completed = False).count()
        categories = Category.objects.filter(shop = shop)
        cart_items = self.request.user.cart_items()
        # print("cart_items:", cart_items)

        cart_p = self.request.user.cart_prods()
        # print("cart_prods:", cart_p)
        p_ids = [x.id for x in cart_p ]
        # print(p_ids)
        prods = Product.objects.filter(pk__in=p_ids)

        slides = Slide.objects.filter(user = shop.user)

        cart = Item.objects.filter(cart=self.request.user.cart)
        # for i in cart_items:
        #     print(i)
        #     cart_p.append(i.product)
        context.update({
            'shop':shop,
            "form":form,
            "categories":categories,
            "current_category":curr_category,
            "cart_items": cart,
            "prods":prods,
            "orders": orders,
            "slides":slides,
        })

        


        return context
          



class ProductListWholeView(LoginRequiredMixin, ListView):    
    template_name = 'shop/product_list_whole.html'

    def form_valid(self):
        print("\n\n\n\n\nasdkjasdbjhabsdjhbasd\n\n\n\n")
        if self.request.POST.get("q"):
            print("\n\n\n\n",self.request.POST.get("q"))


    def get_queryset(self, **kwargs):
        # category = self.kwargs['cat']

        # print(Product.objects.filter(shop__pk = self.kwargs['pk']))
        # queryset.filter(category = category)
        # if self.kwargs['cat'] == 0:
        #     queryset = Product.objects.filter(shop__pk = self.kwargs['pk'])
        # else:
        #     category_item = Category.objects.get(id = category)
        #     queryset = Product.objects.filter(shop__pk = self.kwargs['pk'])
        #     queryset = queryset.filter(category = category_item)
        # print(queryset)
        queryset = Product.objects.all()
        print("get request data", self.request.GET)
        print("post request data", self.request.POST)
        print("kwargs request data", kwargs)
        print("full path request data", self.request.get_full_path())
        param = self.request.get_full_path()
        param = param.split("/")
        print(param)
        param = param[2]
        print(param)

        # print("the passed get request.: ", kwargs["pk"])
        queryset = queryset.filter(name__icontains = param)
        q2 = Product.objects.filter(index__icontains = param)
        print(q2)
        queryset = queryset.union(q2)

shop/templates/shop/category_detail.html
{% extends "base.html" %}{% load tailwind_filters %} {% block content %}

<div class="max-w-7xl mx-auto flex flex-wrap">
    <span class ="text-3xl text-bold">The <em>{{cat}}</em> category has the following Products:</span>
    <div class="inline-block min-w-full py-2 align-middle">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 wx-100 md:rounded-lg">
            <table class="min-w-full divide-y divide-gray-300">
                <thead class="bg-gray-50">
                    <tr>
                        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">#</th>
                        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900">Product</th>
                        <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Currently In-stock</th>
                        <th scope="col" class="px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Price</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-200 bg-white">
                  {% for prod in cat.products.all %}
                  
                    <tr>
                        <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-semibold text-gray-900 sm:pl-6">1</td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{prod.name}}</td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm">
                            {{prod.stock}}
                        </td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm">
                            {% comment %} <span class="flex justify-center">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                                </svg>
                            </span> {% endcomment %}
                            <t/>{{prod.price}}
                        </td>
                    </tr>
                  {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
  </div>


{% endblock %}

shop/templates/shop/home.html
{% extends "base.html" %} {% block content %}
<section class="text-gray-600 body-font">
  <div
    class="container mx-auto flex px-5 py-24 items-center justify-center flex-col"
  >
    <img
      class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded"
      alt="hero"
      src="https://dummyimage.com/720x600"
    />
    <div class="text-center lg:w-2/3 w-full">
      <h1
        class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"
      >
        Microdosing synth tattooed vexillologist
      </h1>
      <p class="mb-8 leading-relaxed">
        Meggings kinfolk echo park stumptown DIY, kale chips beard jianbing
        tousled. Chambray dreamcatcher trust fund, kitsch vice godard disrupt
        ramps hexagon mustache umami snackwave tilde chillwave ugh. Pour-over
        meditation PBR&amp;B pickled ennui celiac mlkshk freegan photo booth af
        fingerstache pitchfork.
      </p>
      <div class="flex justify-center">
        <button
          class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
        >
          Button
        </button>
        <button
          class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg"
        >
          Button
        </button>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

shop/templates/shop/item_update.html
{% extends "base.html" %}{% load tailwind_filters %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <img
        alt="ecommerce"
        class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="/{{prod.img}}"
      />
      <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
        <a href="{% url 'shop:home' pk=prod.shop.id cat=0 %}">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">
            Go back to products in {{prod.shop}}
          </h2>
        </a>
        <h1 class="text-gray-700 text-3xl title-font font-medium mb-1">
          Name: {{prod.name}}
        </h1>
        <h3 class="text-gray-600 text-2xl font-medium mb-1">
          Quantity: {{prod.stock}}
        </h3>
        <h3 class="text-gray-600 text-2xl font-medium mb-1">
          Price: {{prod.price}}
        </h3>
        <h3 class="text-gray-600 text-2xl font-medium mb-1">
          Categories: {{categories}}
        </h3>
        {% if request.user == prod.shop.user %}
        <div class="flex py-6">
          <form method="POST" id="update_form"
          enctype="multipart/form-data"
          >
            {% csrf_token %} {{ form|crispy }}
            <button
              class="flex ml-right text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
              type="submit"
            >
              Update
            </button>
          </form>
        </div>
        {% else %}

        <a href="{% url 'shop:product_compare' pk=prod.id %}">
          <h1 class = "truncate font-bold text-5md bg-gray-300 underline margin-4 px-4 text-right">
            Compare with other shops
          </h1>
        </a>
        <br>
        <hr>
        <h1 class = "truncate font-bold text-4xl bg-gray-200 margin-4 px-4">Add to cart:</h1>
          <!-- {% csrf_token %} -->
          <form method="POST">
            {% csrf_token %} {{ form|crispy }}
            <button type="submit" class = "justify-center ml-right text-white bg-green-400 border-y-200 py-2 px-6 focus:outline-none hover:bg-green-600 rounded">
              Update
            </button>
          </form>
          <br>
          <a href = "{% url "shop:item-delete" item.id %}">
            <button type="submit" class = "justify-center flex ml-right text-white bg-red-600 border-y-200 py-2 px-6 focus:outline-none hover:bg-red-700 rounded">
              Delete {{item}}
            </button>
          </a>
          <h3>{{msg}}</h3>

        {% endif %}
      </div>
    </div>
  </div>
</section>
<script type="text/javascript">
  $(document).on('submit', '#update_form',(function (e) {
      e.preventDefault();
      $.ajax({ // create an AJAX call...
        data: $(this).serialize(), // get the form data
        type: $(this).attr('method'), // GET or POST
        url: $(this).attr('action'), // the file to call
        success: function(response) { // on success..
            $('#success_div').html(response); // update the DIV
        },
        error: function(e, x, r) { // on error..
            $('#error_div').html(e); // update the DIV
        }
    });
  });
</script>
{% endblock content %}

shop/templates/shop/product_update.html
{% extends "base.html" %}{% load tailwind_filters %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <img
        alt="ecommerce"
        class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        {% if prod.img %}
        src="/{{prod.img}}"
        {% else %}
        src="/static/pexels-_getinspoco_-bibhash-banerjee-1047168.jpg"
        {% endif %}
      />
      <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
        <a href="{% url 'shop:home' pk=prod.shop.id cat=0 %}">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">
            Go back to products in {{prod.shop}}
          </h2>
        </a>
        <h1 class="text-gray-700 text-3xl title-font font-medium mb-1">
          Name: {{prod.name}}
        </h1>
        <h3 class="text-gray-600 text-2xl font-medium mb-1">
          Quantity: {{prod.stock}}
        </h3>
        <h3 class="text-gray-600 text-2xl font-medium mb-1">
          Price: {{prod.price}}
        </h3>
        <h3 class="text-gray-600 text-2xl font-medium mb-1">
          Categories: {{categories}}
        </h3>
        {% if request.user == prod.shop.user %}
        <div class="flex py-6">
          <form method="POST" id="update_form"
          enctype="multipart/form-data"
          >
            {% csrf_token %} {{ form|crispy }}
            <button
              class="flex ml-right text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
              type="submit"
            >
              Update
            </button>
          </form>
        </div>
        {% else %}
        <a href="{% url 'shop:product_compare' pk=prod.id %}">
          Compare with other shops</a
        >
        {% if request.user.cart.items.all %}
          {% comment %} {% for it in request.user.cart.items.all %} {% endcomment %}
          {% if prod in prods %}
          {% for it in cart_items %}
              {% if it.product == prod %}
              <button
              class="ml-right text-white bg-indigo-500 justify border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
              >
              <a href = "{% url "shop:item-update" it.id %}">
                <span class = "cart_quan"> Update Quantity
                    {{it.quantity}}</span>
              </a>
              </button>
            
              {% else %}
              {% endif %}
          {% endfor %}
          
            {% else %}
            <button
              class="ml-right text-white bg-indigo-500 justify border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
            >
            <a href = "{% url "shop:item-create" prod.id %}">
              <svg class="w-5 h-5 fill-current justify-right" viewBox="0 0 20 20"><path d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd" fill-rule="evenodd"></path></svg>
              Add to cart
            </a>
            </button>
            {% endif %}
          {% comment %} {% endfor %}  {% endcomment %}

          {% else %}
          <button
            class="ml-right text-white bg-indigo-500 justify border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
          >
          <a href = "{% url "shop:item-create" prod.id %}">
            <svg class="w-5 h-5 fill-current justify-right" viewBox="0 0 20 20"><path d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd" fill-rule="evenodd"></path></svg>
            Add to cart
          </a>
          </button>          
          {% endif %}
          <button
            class="justify-center  ml-right text-white bg-red-600 border-y-200 py-2 px-6 focus:outline-none hover:bg-red-700 rounded"
            style="float: right"
          >
            <a href="#">
              <span class="mt-1">
                <svg class="w-5 h-5 fill-current" viewBox="0 0 20 20"><path d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd" fill-rule="evenodd"></path></svg>
                Wish List
              </span>
            </a>
          </button>


        {% endif %}
      </div>
    </div>
  </div>
</section>
<script type="text/javascript">
  $(document).on('submit', '#update_form',(function (e) {
      e.preventDefault();
      $.ajax({ // create an AJAX call...
        data: $(this).serialize(), // get the form data
        type: $(this).attr('method'), // GET or POST
        url: $(this).attr('action'), // the file to call
        success: function(response) { // on success..
            $('#success_div').html(response); // update the DIV
        },
        error: function(e, x, r) { // on error..
            $('#error_div').html(e); // update the DIV
        }
    });
  });
</script>
{% endblock content %}