base/urls.py
from django.contrib import admin
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.HomeView.as_view(), name = 'home'),
    # path('leads_list', views.LeadListView.as_view(), name = 'leads_list'),
    # path('create', views.LeadCreateView.as_view(), name = "lead_create"),
    # path('detail/<int:pk>', views.LeadDetailView.as_view(), name = 'lead_detail'),
    # path('lead_update/<int:pk>', views.LeadUpdateView.as_view(), name = 'lead_update'),
    # path('lead_delete/<int:pk>', views.LeadDeleteView.as_view(), name = 'lead_delete'),
    # path('assign_agent/<int:pk>', views.AssignAgentView.as_view(), name = "assign_agent"),
    # path('category_update/<int:pk>', views.LeadCategoryUpdateView.as_view(), name = "category_update"),
    # path('category_list', views.CategoryListView.as_view(), name = 'category_list'),
    
    # path('category_detail/<int:pk>', views.CategoryDetailView.as_view(), name = 'category_detail'),

]

shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views

app_name = 'shop' 

urlpatterns = [
    # products
    path('<int:pk>/<int:cat>', views.ProductListView.as_view(), name = 'home'),
    path('<int:pk>/create', views.ProductCreateView.as_view(), name = "product_create"),
    path('delete/<int:pk>', views.ProductDeleteView.as_view(), name = "product_delete"),
    path('update/<int:pk>', views.ProductUpdateView.as_view(), name = "product_update"),
    path('compare/<int:pk>', views.ProductCompareView.as_view(), name = "product_compare"),
    path('<pk>/all', views.ProductListWholeView.as_view(), name = "product_all"),
    
    
    # others
    path('item-create/<int:pk>', views.ItemCreateView.as_view(), name = 'item-create'),
    path('item-update/<int:pk>', views.ItemUpdateView.as_view(), name = 'item-update'),
    path('item-delete/<int:pk>', views.ItemDeleteView.as_view(), name = 'item-delete'),
    path('order-create/<int:pk>', views.OrderCreateView.as_view(), name = 'order-create'),
    path('order-list/<int:pk>', views.OrderListView.as_view(), name = 'order-list'),
    path('order-list-customer/<int:pk>', views.OrderListCustomerView.as_view(), name = 'order-list-customer'),
    path('order-update/<int:pk>', views.OrderUpdateView.as_view(), name = 'order-update'),
    path('order-delete/<int:pk>', views.OrderDeleteView.as_view(), name = 'order-delete'),
    path('order-detail-customer/<int:pk>', views.OrderDetailViewCustomer, name = 'order-detail-customer'),
    path('stock-update/<int:pk>', views.StockUpdateView, name = 'stock-update'),
    path('map-index', views.map_index, name = 'map-index'),


    # categories
    path('<int:pk>/categories', views.category_create, name = 'categories'),
    path('category-delete/<int:pk>', views.category_delete, name = 'category-delete'),
    path('category-detail/<int:pk>', views.CategoryDetailView.as_view(), name = 'category-detail'),


    # suppliers
    path('<int:pk>/suppliers', views.supplier_create, name = 'suppliers'),
    path('supplier-update/<int:pk>', views.SupplierUpdateView.as_view(), name = 'supplier-update'),
    path('supplier-delete/<int:pk>', views.supplier_delete, name = 'supplier-delete'),
    path('supplier-detail/<int:pk>', views.SupplierDetailView.as_view(), name = 'supplier-detail'),

    # slides
    path('slide-create/<int:pk>', views.SlideCreateView.as_view(), name = 'slide-create'),
    path('slide-list/<int:pk>', views.SlideListView.as_view(), name = 'slide-list'),
    path('slide-delete/<int:pk>', views.SlideDeleteView, name = 'slide-delete'),

    # shop
    path('shop-update/<int:pk>', views.ShopUpdateView.as_view(), name = 'shop-update'),
    path('shop-confirm-user', views.confirm_user_view, name = 'confirm-user'),
    path('update-bank-detail/<int:pk>', views.BankDetailUpdateView.as_view(), name = 'update-bank'),

]

smart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
        LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, 
        PasswordResetConfirmView, PasswordResetCompleteView, 
    )
from base.views import SignupView, ProfileDetailView, CartView ,CheckoutDetailView, ProfileUpdateView
from shop.views import payment_handler_with_order_id, success, CheckoutDetailView, payment_handler, ShopCreateView
# from leads.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace = 'base')),
    path('shop/', include('shop.urls', namespace = 'shop')),
    path('login/', LoginView.as_view(),name = 'login'),
    path('logout/', LogoutView.as_view(),name = 'logout'),
    path('profile/<int:pk>', ProfileDetailView.as_view(),name = 'profile'),
    path('profile-update/<int:pk>', ProfileUpdateView.as_view(),name = 'profile-update'),
    path('cart/<int:pk>', CartView,name = 'cart'),
    # path('checkout/<int:pk>', CheckoutDetailView,name = 'checkout'),
    path('checkout/<int:pk>', CheckoutDetailView.as_view(),name = 'checkout'),
    path('signup/', SignupView.as_view(),name = 'signup'),
    # path('password_reset/', PasswordResetView.as_view(),name = 'password_reset'),
    # path('payment/<int:pk>', payment_handler_with_order_id, name = 'payment'),
    path('payment/<int:pk>', payment_handler, name = 'payment'),
    path('success', success, name = 'success-payment'),
    path('password_reset/', PasswordResetView.as_view(),name = 'password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(),name = 'password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name = 'password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(),name = 'password_reset_complete'),

    # shop views
    path("shop_create", ShopCreateView.as_view(), name="shop-create")
    
]

base/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MaxValueValidator, MinValueValidator 

# Create your models here.




class User(AbstractUser):
    pfp = models.ImageField(upload_to = 'static/users', blank = True, null = True)
    address = models.CharField(max_length=100, blank = True, null = True)
    phone = models.BigIntegerField(null = True, blank = True, unique = True)
    email = models.CharField(max_length=50, blank = True, null = True)


    
    def cart_items(self):
        cart_items = {}
        # print(cart_items[[str(a).split(" ")[0]] = a.quantity for a in self.cart.items.all()])
        for a in self.cart.items.all():
            cart_items[str(a).split(" ")[0]] = a.quantity
        print(cart_items)
        return cart_items
    def cart_prods(self):
        cart_items = []
        # print(cart_items[[str(a).split(" ")[0]] = a.quantity for a in self.cart.items.all()])
        for a in self.cart.items.all():
            cart_items.append(a.product)
        print(cart_items)
        return cart_items


class Shop(models.Model):
    cat_choices = (
        ('General', 'GEN'),
        ('Dairy', 'DRY'),
        ('Bakery', 'BKR'),
    )

    name = models.CharField(max_length=50)
    pfp = models.ImageField(upload_to = 'static/shops', blank = True, null = True)
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null = True, blank = True, related_name = "shop")
    category = models.CharField(choices = cat_choices,max_length= 100)
    
    open_time = models.TimeField()
    close_time = models.TimeField()
    phone = models.BigIntegerField(null = True, blank = True, unique = True)
    email = models.EmailField(null = True, blank = True, unique = True)

    address = models.CharField(max_length=200, null=True, blank=True) 

    rzp_pr_key = models.CharField(max_length=400, default = "omFNDCkZBgjorzpFzNNmfKyd") 
    rzp_pb_key = models.CharField(max_length=400, default = "rzp_test_0ovBWEVK2aFRht")


    def __str__(self):
        return self.name



class Notifications(models.Model):
    description = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank = True, null = True)

base/forms.py
from django import forms
from .models import User, Shop
from shop.models import Order
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model
from phonenumber_field.formfields import PhoneNumberField

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', "email", "phone", 'pfp', 'address')
        # field_classes = {'username': UsernameField}

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        self.fields['phone'].widget = forms.TextInput(attrs={
            'id': 'phone_field',
            "min":"1000000000",
            "max":"9999999999",
            "type":"number",
            })
        self.fields['email'].widget = forms.TextInput(attrs={"type":"email"})



class ConfirmUserForm(forms.Form):
    # class Meta:
    #     model = User
    #     fields = ('username', "Password")
        
    #     # field_classes = {'username': UsernameField}
    
    # def __init__(self, *args, **kwargs):
    #     super(ConfirmUserForm, self).__init__(*args, **kwargs)
        
    #     self.fields['password'].widget = forms.PasswordInput()
    username = forms.CharField(initial = "")
    password = forms.CharField(widget=forms.PasswordInput(), initial = "")

class UpdateBankDetailsForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ('rzp_pr_key', "rzp_pb_key")
        
        # field_classes = {'username': UsernameField}
    
    def __init__(self, *args, **kwargs):
        super(UpdateBankDetailsForm, self).__init__(*args, **kwargs)
        
        self.fields['rzp_pr_key'].label = "Razorpay Private Key"
        self.fields['rzp_pb_key'].label = "Razorpay Public Key"




class ShopCreateForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ('name', "category", "pfp", "open_time", "close_time", "phone", "email", "address","rzp_pr_key", "rzp_pb_key")
        
    def __init__(self, *args, **kwargs):
        super(ShopCreateForm, self).__init__(*args, **kwargs)
        self.fields['close_time'].widget = forms.DateInput(attrs={'class':'timepicker'})
        self.fields['rzp_pr_key'].label = "Enter Razorpay Public Key"
        self.fields['rzp_pb_key'].label = "Enter Razorpay Private Key"
        self.fields['rzp_pr_key'].widget = forms.PasswordInput( )
        self.fields['rzp_pb_key'].widget = forms.PasswordInput()
        self.fields['rzp_pb_key'].initial = ""
        self.fields['rzp_pr_key'].initial = ""

        self.fields['phone'].widget = forms.TextInput(attrs={
            'id': 'phone_field',
            "min":"1000000000",
            "max":"9999999999",
            "type":"number",
            })
        self.fields['email'].widget = forms.TextInput(attrs={"type":"email"})





class ShopUpdateForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ('name', "pfp", "open_time", "close_time", "phone", "email", "address")
        # widgets = {
        #     'phone':PhoneNumberField()
            # "open_time":forms.TimeField(),
            # "close_time":forms.TimeField(),
        # }
    def __init__(self, *args, **kwargs):
        super(ShopUpdateForm, self).__init__(*args, **kwargs)
        self.fields['phone'].widget = forms.TextInput(attrs={
            'id': 'phone_field',
            "min":"1000000000",
            "max":"9999999999",
            "type":"number",
            })
        self.fields['email'].widget = forms.TextInput(attrs={"type":"email"})



class CustomUserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', "email", "phone", 'pfp', 'address')
        # field_classes = {'username': UsernameField}
        



class OrderCreateForm(forms.Form):
    class Meta:
        model = Order
        fields = ('address', 'description', )

base/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from .models import Shop, User
from shop.models import Item, Cart, Slide
# from .forms import LeadForm, LeadModelForm, CustomUserCreationForm, AssignAgentForm, LeadCategoryUpdateForm
from .forms import CustomUserCreationForm, CustomUserUpdateForm
from django.shortcuts import redirect, reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
# from agents.mixins import OrganiserLoginRequiredMixin

# Create your views here.


class HomeView(LoginRequiredMixin, ListView):
    template_name = 'base/shop_list.html'

    def get_context_data(self, **kwargs):
        superusers = User.objects.get(is_superuser=True)
        context = super().get_context_data(**kwargs)
        slides = Slide.objects.filter(user = superusers)
        sl1 = Slide.objects.first()
        context.update({
            'slides':slides,
            'sl':sl1,
            "hello":"asdasdsadsad"
            # 'categories':prod.get_categories()
        })
        return context
    
    def form_valid(self, **kwargs):
        print(self)
        print(kwargs)
        print("\n\n\n\n\nasdkjasdbjhabsdjhbasd\n\n\n\n")
        if self.request.GET.get("q"):
            print("\n\n\n\n",self.request.POST.get("q"))

    def get(self, *args, **kwargs):
        pass


    def get_queryset(self, **kwargs):
        queryset = Shop.objects.all()
        return queryset
    


    def get(self, *args, **kwargs):
        try:
            if self.request.user.shop:
                return redirect('shop:home', pk=self.request.user.shop.id, cat=0)
        except:
            if self.request.GET:
                print(self.request.GET.get("q"))
                return redirect("shop:product_all", pk = self.request.GET.get("q"))
            return super(HomeView, self).get(*args, **kwargs)
            # return super(HomeView, self).get(*args, **kwargs)



class SignupView(CreateView):
    template_name = "registration/user_create.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")



class ProfileDetailView(LoginRequiredMixin, DetailView):
    template_name = 'registration/user_detail.html'
    context_object_name = 'user'


    def get_queryset(self):
        return User.objects.all()




class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'registration/user_detail.html'
    context_object_name = 'user'


    def get_queryset(self):
        return User.objects.all()



class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'registration/user_update.html'
    form_class = CustomUserUpdateForm

    
    def get_context_data(self, **kwargs):
        curr_supp = User.objects.get(id = self.kwargs["pk"])
        form = CustomUserUpdateForm(instance = curr_supp)
        # supp_id = self.kwargs['pk']
        
        # supp = Supplier.objects.get(id = supp_id)
        # print(prod)
        # queryset = Supplier.objects.get(id = supp_id)
        context = super().get_context_data(**kwargs)
        context.update({
            'supplier':curr_supp,
            # 'categories':prod.get_categories()
        })
        print(curr_supp)
        return context
    
    
    def get_queryset(self): 
        user = self.request.user
        # supp_id = self.kwargs["pk"]

        # supp = Supplier.objects.get(id= supp_id)
        queryset = User.objects.filter(id = user.id)
        return queryset

    
    def get_success_url(self):
        return reverse('profile', kwargs = {'pk': self.kwargs['pk']})



def CartView(request, pk):
    msg = ''
    user = request.user
    print(user)
    shops = Shop.objects.all()
    items = request.user.cart.items.all()
    total = {}
    shops = set()
    for i in items:
        shops.add(i.product.shop)
        # if str(i.product.shop.id) in  total:
        if i.product.shop.id in  total:
            # total[str(i.product.shop.id)] += i.product.price * i.quantity
            total[i.product.shop.id] += i.product.price * i.quantity

        else:
            # total[str(i.product.shop.id)] = i.product.price * i.quantity
            total[i.product.shop.id] = i.product.price * i.quantity

    print(total)
    context = {'msg':msg, 'items': items, 'shops': shops, 'total':total}
    return render(request , 'base/cart.html', context)





def CheckoutDetailView(req, pk):

    return HttpResponse("asdadas")

base/templates/base/cart.html
{% extends "base.html" %} {% load tailwind_filters %}{% block content %}
<div class="w-full max-w-screen-xl mx-auto px-6">
  <div class="bg-yellow-200 rounded-lg px-5 py-4 mb-4">
    <h1 class="text-5xl font-black font-mono" style = "font-family:Arial; font-weight:300;">Items in Your Cart</h1>
  </div>
  <div class="flex justify-center p-4 px-3 py-10">
    <div class="w-full inline-flex" style = "flex-wrap:wrap">
      {% for shop in shops %}
      <div
        class="bg-white max-w-md shadow-md rounded-lg px-3 py-2 mb-4"
        style="margin-left: 40px; height:fit-content; width:30%"
      >
        <div
          class="block text-gray-700 text-lg font-semibold py-2 px-2"
          style="font-size: 28px; font-weight: bold; postion: relative"
        >
          Items from store: {{shop}}
        </div>
        {% for item in items %} {% if item.product.shop == shop %}
        <a href="{% url 'shop:item-update' item.id %}">
          <div class="py-3 text-sm">
            <div
              class="flex justify-start cursor-pointer text-gray-700 hover:text-blue-400 hover:bg-blue-100 rounded-md px-2 py-2 my-2"
            >
              <span class="bg-gray-400 h-2 w-2 m-2 rounded-full"></span>
              <div
                class="flex-grow font-medium px-2"
                style="font-size: 18px; font-weight: bold"
              >
                {{item.product}}
                <span
                  class="inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-indigo-500 bg-yellow-200 rounded-full"
                  style="margin-left: 20px; font-size: 18px; word-wrap:break-word; display:block;"
                >
                  {{item.quantity}} Units @ ₹{{item.product.price}}</span
                >
              </div>

              <div
                class="text-sm font-normal text-gray-500 tracking-wide"
                style="margin-left: 70px; font-size: 18px;"
              >
                {% widthratio item.product.price 1 item.quantity %}
              </div>
            </div>
          </div>
        </a>
        {% endif %} {% endfor %}
        <div
          class="flex max-w-md bg-gray-200 text-sm text-left py-2 px-3 -mx-3 -mb-2 rounded-b-lg"
          style="postion: absolute; bottom: 0"
        >
          {% for sh,tot in total.items %} {% if sh == shop.id %} Total :
          ₹{{tot}} {% else %} {% endif %} {% endfor %}
        </div>
        <div id = "aksjndsakjn"
          class="flexblock max-w-md bg-gray-200 text-sm text-right py-2 px-3 -mx-3 -mb-2 rounded-b-lg">
          <a href="{% url 'checkout' shop.id %}">
            <button
              class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
            >
              CheckOut
            </button>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{{msg}}{% endblock content %}

base/templates/base/checkout.html
{% extends "base.html" %} {% load tailwind_filters %}{% block content %}
<div class="w-full max-w-screen-xl mx-auto px-6">
  <div class="bg-yellow-200 rounded-lg px-5 py-4 mb-4">
    <h1 class="text-5xl font-black font-mono" style = "font-family:Arial; font-weight:300;">Payment to: {{ shop_current}}</h1>
  </div>
  <div class="bg-yellow-200 rounded-lg px-5 py-4 mb-4" style:"margin-top:5px">
  <h1 class="text-5xl font-black font-mono" style = "font-family:Arial; font-weight:300;">Total: ₹{{ total}}</h1>
</div>
<div class="flex justify-center p-4 px-3 py-10 bg-white max-w-md shadow-md rounded-lg px-3 py-2 mb-4">
  <div class="w-full inline-flex">
    <div
      class="block text-gray-700 text-lg font-semibold py-2 px-2"
      style="font-size: 28px; font-weight: bold"
    >
      Items: {{shop}}
    </div>
    {% for item in object_list %}
    <div
      class="block text-gray-700 text-lg font-semibold py-2 px-2"
      style="font-size: 28px; font-weight: bold"
    >
      <a href="{% url 'shop:item-update' item.id %}">
        <div class="py-3 text-sm">
          <div
            class="flex justify-start cursor-pointer text-gray-700 hover:text-blue-400 hover:bg-blue-100 rounded-md px-2 py-2 my-2"
          >
            <span class="bg-gray-400 h-2 w-2 m-2 rounded-full"></span>
            <div
              class="flex-grow font-medium px-2"
              style="font-size: 18px; font-weight: bold"
            >
              {{item.product}}
              <span
                class="inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-indigo-500 bg-yellow-200 rounded-full"
                style="margin-left: 20px; font-size: 18px"
              >
                {{item.quantity}} Units @ Rs. {{item.product.price}}</span
              >
            </div>

            <div
              class="text-sm font-normal text-gray-500 tracking-wide"
              style="margin-left: 70px; font-size: 18px; font-weight: bold"
            >
              {% widthratio item.product.price 1 item.quantity %}
            </div>
          </div>
        </div>
      </a>
      <div>
        {% endfor %}
        <div
          class="block max-w-md bg-gray-200 text-sm text-right py-2 px-3 -mx-3 -mb-2 rounded-b-lg"
        >
          {{shop.id}}
          <a href="{% url 'shop:order-create' shop_current.id %}">
            <button
              class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
            >
              Confirm Order
            </button>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{{msg}}{% endblock content %}



<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14233.980183334597!2d80.84331375000001!3d26.88777975!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x399bfe1eb4f1978d%3A0x30bbbe96c52297e2!2sUnity%20PG%20College%20-%20Best%20Private%20PG%20%26%20LAW%20College%20For%20BTC%2C%20BA%2C%20B.Com%2C%20BBA!5e0!3m2!1sen!2sin!4v1652273112369!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

base/templates/base/home.html
{% extends "base.html" %} {% block content %}
<section class="text-gray-600 body-font">
  <div
    class="container mx-auto flex px-5 py-24 items-center justify-center flex-col"
  >
    <div class="text-center lg:w-2/3 w-full">
      <div class="flex justify-center">
        <button
          class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
        >
          Button
        </button>
        <button
          class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg"
        >
          Button
        </button>
      </div>
    </div>
  </div>
</section>

{% endblock content %}